name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Install Nix
        uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check tasks
        run: nix develop -c ./check.sh
      - name: Run shellcheck on scripts
        run: nix develop -c sh -c "find . -name '*.sh' -exec shellcheck {} \\;"
      
      
